"""create vacancies

Revision ID: 4dbb1170847c
Revises:
Create Date: 2026-05-19 08:17:07.350769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dbb1170847c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("apply_link", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("company_stars", sa.String(), nullable=True),
        sa.Column("salary", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("work_location", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.Column("published_at", sa.String(), nullable=True),
        sa.Column("work_experience", sa.String(), nullable=True),
        sa.Column("work_formats", sa.JSON(), nullable=False),
        sa.Column("employment_types", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancies")),
    )
    op.create_index(
        op.f("ix_vacancies_apply_link"), "vacancies", ["apply_link"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacancies_apply_link"), table_name="vacancies")
    op.drop_table("vacancies")
    # ### end Alembic commands ###
