"""create search history

Revision ID: 6dbcdcc3ee81
Revises: 9a8f1a647612
Create Date: 2026-05-29 17:05:25.992892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dbcdcc3ee81"
down_revision: Union[str, Sequence[str], None] = "9a8f1a647612"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "searches",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("max_vacancies", sa.Integer(), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "CANCELED",
                "FINISHED",
                "FAILED",
                name="searchstatusapischema",
            ),
            nullable=False,
        ),
        sa.Column("parsed_vacancies", sa.Integer(), nullable=False),
        sa.Column("parsed_pages", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_searches")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("searches")
    # ### end Alembic commands ###
