"""create rate limits

Revision ID: 9a8f1a647612
Revises: b3aa66028b28
Create Date: 2026-05-27 11:49:21.868191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a8f1a647612"
down_revision: Union[str, Sequence[str], None] = "b3aa66028b28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limits")),
    )
    op.add_column("vacancies", sa.Column("response_link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "response_link")
    op.drop_table("rate_limits")
    # ### end Alembic commands ###
