"""create settings

Revision ID: b3aa66028b28
Revises: f6b5f9cefc8b
Create Date: 2026-05-22 20:47:14.823930

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3aa66028b28"
down_revision: Union[str, Sequence[str], None] = "f6b5f9cefc8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("letter_style", sa.String(), nullable=False),
        sa.Column("resume_text", sa.String(), nullable=False),
        sa.Column("daily_limit", sa.Integer(), nullable=False),
        sa.Column("hourly_limit", sa.Integer(), nullable=False),
        sa.Column("min_delay_ms", sa.Integer(), nullable=False),
        sa.Column("delay_jitter_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_settings_ck_settings_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
