"""add llm settings column

Revision ID: f2014206e0e7
Revises: 6dbcdcc3ee81
Create Date: 2026-06-03 15:04:22.734063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2014206e0e7"
down_revision: Union[str, Sequence[str], None] = "6dbcdcc3ee81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.Enum(
                "PENDING",
                "RUNNING",
                "CANCELED",
                "FINISHED",
                "FAILED",
                "INTERRUPTED",
                name="searchstatusapischema",
            ),
            existing_nullable=False,
        )

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "llm_deployments",
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )
        batch_op.add_column(sa.Column("llm_system_prompt", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("llm_system_prompt")
        batch_op.drop_column("llm_deployments")

    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PENDING",
                "RUNNING",
                "CANCELED",
                "FINISHED",
                "FAILED",
                "INTERRUPTED",
                name="searchstatusapischema",
            ),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
