"""create cover letters

Revision ID: f6b5f9cefc8b
Revises: cca6d6365faa
Create Date: 2026-05-21 10:33:11.829700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6b5f9cefc8b"
down_revision: Union[str, Sequence[str], None] = "cca6d6365faa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cover_letters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_cover_letters_application_id_applications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cover_letters")),
    )
    op.create_index(
        op.f("ix_cover_letters_application_id"),
        "cover_letters",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cover_letters_application_id"), table_name="cover_letters")
    op.drop_table("cover_letters")
    # ### end Alembic commands ###
